// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/collection.proto

package org.mojolang.mojo.postman;

public final class CollectionProto {
  private CollectionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Collection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Collection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mojo/postman/collection.proto\022\014mojo.po" +
      "stman\032\027mojo/postman/info.proto\032\027mojo/pos" +
      "tman/item.proto\032\033mojo/postman/variable.p" +
      "roto\"z\n\nCollection\022 \n\004info\030\001 \001(\0132\022.mojo." +
      "postman.Info\022 \n\004item\030\002 \003(\0132\022.mojo.postma" +
      "n.Item\022(\n\010variable\030\005 \003(\0132\026.mojo.postman." +
      "VariableBh\n\031org.mojolang.mojo.postmanB\017C" +
      "ollectionProtoP\001Z8github.com/mojo-lang/p" +
      "ostman/go/pkg/mojo/postman;postmanb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.postman.InfoProto.getDescriptor(),
          org.mojolang.mojo.postman.ItemProto.getDescriptor(),
          org.mojolang.mojo.postman.VariableProto.getDescriptor(),
        });
    internal_static_mojo_postman_Collection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Collection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Collection_descriptor,
        new java.lang.String[] { "Info", "Item", "Variable", });
    org.mojolang.mojo.postman.InfoProto.getDescriptor();
    org.mojolang.mojo.postman.ItemProto.getDescriptor();
    org.mojolang.mojo.postman.VariableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
