// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/collection.proto

package org.mojolang.mojo.postman;

public interface CollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Collection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.postman.Info info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.mojo.postman.Info info = 1;</code>
   * @return The info.
   */
  org.mojolang.mojo.postman.Info getInfo();
  /**
   * <code>.mojo.postman.Info info = 1;</code>
   */
  org.mojolang.mojo.postman.InfoOrBuilder getInfoOrBuilder();

  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Item> 
      getItemList();
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  org.mojolang.mojo.postman.Item getItem(int index);
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  int getItemCount();
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.ItemOrBuilder> 
      getItemOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  org.mojolang.mojo.postman.ItemOrBuilder getItemOrBuilder(
      int index);

  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Variable> 
      getVariableList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  org.mojolang.mojo.postman.Variable getVariable(int index);
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  int getVariableCount();
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
      getVariableOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
      int index);
}
