// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/collection.proto

package org.mojolang.mojo.postman;

/**
 * Protobuf type {@code mojo.postman.Collection}
 */
public final class Collection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.postman.Collection)
    CollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Collection.newBuilder() to construct.
  private Collection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Collection() {
    item_ = java.util.Collections.emptyList();
    variable_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Collection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.postman.CollectionProto.internal_static_mojo_postman_Collection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.postman.CollectionProto.internal_static_mojo_postman_Collection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.postman.Collection.class, org.mojolang.mojo.postman.Collection.Builder.class);
  }

  public static final int INFO_FIELD_NUMBER = 1;
  private org.mojolang.mojo.postman.Info info_;
  /**
   * <code>.mojo.postman.Info info = 1;</code>
   * @return Whether the info field is set.
   */
  @java.lang.Override
  public boolean hasInfo() {
    return info_ != null;
  }
  /**
   * <code>.mojo.postman.Info info = 1;</code>
   * @return The info.
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.Info getInfo() {
    return info_ == null ? org.mojolang.mojo.postman.Info.getDefaultInstance() : info_;
  }
  /**
   * <code>.mojo.postman.Info info = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.InfoOrBuilder getInfoOrBuilder() {
    return info_ == null ? org.mojolang.mojo.postman.Info.getDefaultInstance() : info_;
  }

  public static final int ITEM_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.mojolang.mojo.postman.Item> item_;
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.postman.Item> getItemList() {
    return item_;
  }
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.postman.ItemOrBuilder> 
      getItemOrBuilderList() {
    return item_;
  }
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  @java.lang.Override
  public int getItemCount() {
    return item_.size();
  }
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.Item getItem(int index) {
    return item_.get(index);
  }
  /**
   * <code>repeated .mojo.postman.Item item = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.ItemOrBuilder getItemOrBuilder(
      int index) {
    return item_.get(index);
  }

  public static final int VARIABLE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.mojolang.mojo.postman.Variable> variable_;
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.postman.Variable> getVariableList() {
    return variable_;
  }
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
      getVariableOrBuilderList() {
    return variable_;
  }
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  @java.lang.Override
  public int getVariableCount() {
    return variable_.size();
  }
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.Variable getVariable(int index) {
    return variable_.get(index);
  }
  /**
   * <code>repeated .mojo.postman.Variable variable = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
      int index) {
    return variable_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (info_ != null) {
      output.writeMessage(1, getInfo());
    }
    for (int i = 0; i < item_.size(); i++) {
      output.writeMessage(2, item_.get(i));
    }
    for (int i = 0; i < variable_.size(); i++) {
      output.writeMessage(5, variable_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (info_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInfo());
    }
    for (int i = 0; i < item_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, item_.get(i));
    }
    for (int i = 0; i < variable_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, variable_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.postman.Collection)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.postman.Collection other = (org.mojolang.mojo.postman.Collection) obj;

    if (hasInfo() != other.hasInfo()) return false;
    if (hasInfo()) {
      if (!getInfo()
          .equals(other.getInfo())) return false;
    }
    if (!getItemList()
        .equals(other.getItemList())) return false;
    if (!getVariableList()
        .equals(other.getVariableList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInfo()) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
    }
    if (getItemCount() > 0) {
      hash = (37 * hash) + ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getItemList().hashCode();
    }
    if (getVariableCount() > 0) {
      hash = (37 * hash) + VARIABLE_FIELD_NUMBER;
      hash = (53 * hash) + getVariableList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.postman.Collection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Collection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Collection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Collection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.postman.Collection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.postman.Collection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.postman.Collection)
      org.mojolang.mojo.postman.CollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.postman.CollectionProto.internal_static_mojo_postman_Collection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.postman.CollectionProto.internal_static_mojo_postman_Collection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.postman.Collection.class, org.mojolang.mojo.postman.Collection.Builder.class);
    }

    // Construct using org.mojolang.mojo.postman.Collection.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      if (itemBuilder_ == null) {
        item_ = java.util.Collections.emptyList();
      } else {
        item_ = null;
        itemBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (variableBuilder_ == null) {
        variable_ = java.util.Collections.emptyList();
      } else {
        variable_ = null;
        variableBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.postman.CollectionProto.internal_static_mojo_postman_Collection_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Collection getDefaultInstanceForType() {
      return org.mojolang.mojo.postman.Collection.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Collection build() {
      org.mojolang.mojo.postman.Collection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Collection buildPartial() {
      org.mojolang.mojo.postman.Collection result = new org.mojolang.mojo.postman.Collection(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.mojolang.mojo.postman.Collection result) {
      if (itemBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          item_ = java.util.Collections.unmodifiableList(item_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.item_ = item_;
      } else {
        result.item_ = itemBuilder_.build();
      }
      if (variableBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          variable_ = java.util.Collections.unmodifiableList(variable_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.variable_ = variable_;
      } else {
        result.variable_ = variableBuilder_.build();
      }
    }

    private void buildPartial0(org.mojolang.mojo.postman.Collection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.info_ = infoBuilder_ == null
            ? info_
            : infoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.postman.Collection) {
        return mergeFrom((org.mojolang.mojo.postman.Collection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.postman.Collection other) {
      if (other == org.mojolang.mojo.postman.Collection.getDefaultInstance()) return this;
      if (other.hasInfo()) {
        mergeInfo(other.getInfo());
      }
      if (itemBuilder_ == null) {
        if (!other.item_.isEmpty()) {
          if (item_.isEmpty()) {
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureItemIsMutable();
            item_.addAll(other.item_);
          }
          onChanged();
        }
      } else {
        if (!other.item_.isEmpty()) {
          if (itemBuilder_.isEmpty()) {
            itemBuilder_.dispose();
            itemBuilder_ = null;
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000002);
            itemBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemFieldBuilder() : null;
          } else {
            itemBuilder_.addAllMessages(other.item_);
          }
        }
      }
      if (variableBuilder_ == null) {
        if (!other.variable_.isEmpty()) {
          if (variable_.isEmpty()) {
            variable_ = other.variable_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureVariableIsMutable();
            variable_.addAll(other.variable_);
          }
          onChanged();
        }
      } else {
        if (!other.variable_.isEmpty()) {
          if (variableBuilder_.isEmpty()) {
            variableBuilder_.dispose();
            variableBuilder_ = null;
            variable_ = other.variable_;
            bitField0_ = (bitField0_ & ~0x00000004);
            variableBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariableFieldBuilder() : null;
          } else {
            variableBuilder_.addAllMessages(other.variable_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              org.mojolang.mojo.postman.Item m =
                  input.readMessage(
                      org.mojolang.mojo.postman.Item.parser(),
                      extensionRegistry);
              if (itemBuilder_ == null) {
                ensureItemIsMutable();
                item_.add(m);
              } else {
                itemBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 42: {
              org.mojolang.mojo.postman.Variable m =
                  input.readMessage(
                      org.mojolang.mojo.postman.Variable.parser(),
                      extensionRegistry);
              if (variableBuilder_ == null) {
                ensureVariableIsMutable();
                variable_.add(m);
              } else {
                variableBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.postman.Info info_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.postman.Info, org.mojolang.mojo.postman.Info.Builder, org.mojolang.mojo.postman.InfoOrBuilder> infoBuilder_;
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     * @return The info.
     */
    public org.mojolang.mojo.postman.Info getInfo() {
      if (infoBuilder_ == null) {
        return info_ == null ? org.mojolang.mojo.postman.Info.getDefaultInstance() : info_;
      } else {
        return infoBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public Builder setInfo(org.mojolang.mojo.postman.Info value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
      } else {
        infoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public Builder setInfo(
        org.mojolang.mojo.postman.Info.Builder builderForValue) {
      if (infoBuilder_ == null) {
        info_ = builderForValue.build();
      } else {
        infoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public Builder mergeInfo(org.mojolang.mojo.postman.Info value) {
      if (infoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          info_ != null &&
          info_ != org.mojolang.mojo.postman.Info.getDefaultInstance()) {
          getInfoBuilder().mergeFrom(value);
        } else {
          info_ = value;
        }
      } else {
        infoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public Builder clearInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public org.mojolang.mojo.postman.Info.Builder getInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    public org.mojolang.mojo.postman.InfoOrBuilder getInfoOrBuilder() {
      if (infoBuilder_ != null) {
        return infoBuilder_.getMessageOrBuilder();
      } else {
        return info_ == null ?
            org.mojolang.mojo.postman.Info.getDefaultInstance() : info_;
      }
    }
    /**
     * <code>.mojo.postman.Info info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.postman.Info, org.mojolang.mojo.postman.Info.Builder, org.mojolang.mojo.postman.InfoOrBuilder> 
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.postman.Info, org.mojolang.mojo.postman.Info.Builder, org.mojolang.mojo.postman.InfoOrBuilder>(
                getInfo(),
                getParentForChildren(),
                isClean());
        info_ = null;
      }
      return infoBuilder_;
    }

    private java.util.List<org.mojolang.mojo.postman.Item> item_ =
      java.util.Collections.emptyList();
    private void ensureItemIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        item_ = new java.util.ArrayList<org.mojolang.mojo.postman.Item>(item_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Item, org.mojolang.mojo.postman.Item.Builder, org.mojolang.mojo.postman.ItemOrBuilder> itemBuilder_;

    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Item> getItemList() {
      if (itemBuilder_ == null) {
        return java.util.Collections.unmodifiableList(item_);
      } else {
        return itemBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public int getItemCount() {
      if (itemBuilder_ == null) {
        return item_.size();
      } else {
        return itemBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public org.mojolang.mojo.postman.Item getItem(int index) {
      if (itemBuilder_ == null) {
        return item_.get(index);
      } else {
        return itemBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder setItem(
        int index, org.mojolang.mojo.postman.Item value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.set(index, value);
        onChanged();
      } else {
        itemBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder setItem(
        int index, org.mojolang.mojo.postman.Item.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder addItem(org.mojolang.mojo.postman.Item value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(value);
        onChanged();
      } else {
        itemBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder addItem(
        int index, org.mojolang.mojo.postman.Item value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(index, value);
        onChanged();
      } else {
        itemBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder addItem(
        org.mojolang.mojo.postman.Item.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.add(builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder addItem(
        int index, org.mojolang.mojo.postman.Item.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder addAllItem(
        java.lang.Iterable<? extends org.mojolang.mojo.postman.Item> values) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, item_);
        onChanged();
      } else {
        itemBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder clearItem() {
      if (itemBuilder_ == null) {
        item_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        itemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public Builder removeItem(int index) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.remove(index);
        onChanged();
      } else {
        itemBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public org.mojolang.mojo.postman.Item.Builder getItemBuilder(
        int index) {
      return getItemFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public org.mojolang.mojo.postman.ItemOrBuilder getItemOrBuilder(
        int index) {
      if (itemBuilder_ == null) {
        return item_.get(index);  } else {
        return itemBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.postman.ItemOrBuilder> 
         getItemOrBuilderList() {
      if (itemBuilder_ != null) {
        return itemBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(item_);
      }
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public org.mojolang.mojo.postman.Item.Builder addItemBuilder() {
      return getItemFieldBuilder().addBuilder(
          org.mojolang.mojo.postman.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public org.mojolang.mojo.postman.Item.Builder addItemBuilder(
        int index) {
      return getItemFieldBuilder().addBuilder(
          index, org.mojolang.mojo.postman.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Item item = 2;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Item.Builder> 
         getItemBuilderList() {
      return getItemFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Item, org.mojolang.mojo.postman.Item.Builder, org.mojolang.mojo.postman.ItemOrBuilder> 
        getItemFieldBuilder() {
      if (itemBuilder_ == null) {
        itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.postman.Item, org.mojolang.mojo.postman.Item.Builder, org.mojolang.mojo.postman.ItemOrBuilder>(
                item_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        item_ = null;
      }
      return itemBuilder_;
    }

    private java.util.List<org.mojolang.mojo.postman.Variable> variable_ =
      java.util.Collections.emptyList();
    private void ensureVariableIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        variable_ = new java.util.ArrayList<org.mojolang.mojo.postman.Variable>(variable_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Variable, org.mojolang.mojo.postman.Variable.Builder, org.mojolang.mojo.postman.VariableOrBuilder> variableBuilder_;

    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Variable> getVariableList() {
      if (variableBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variable_);
      } else {
        return variableBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public int getVariableCount() {
      if (variableBuilder_ == null) {
        return variable_.size();
      } else {
        return variableBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public org.mojolang.mojo.postman.Variable getVariable(int index) {
      if (variableBuilder_ == null) {
        return variable_.get(index);
      } else {
        return variableBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder setVariable(
        int index, org.mojolang.mojo.postman.Variable value) {
      if (variableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableIsMutable();
        variable_.set(index, value);
        onChanged();
      } else {
        variableBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder setVariable(
        int index, org.mojolang.mojo.postman.Variable.Builder builderForValue) {
      if (variableBuilder_ == null) {
        ensureVariableIsMutable();
        variable_.set(index, builderForValue.build());
        onChanged();
      } else {
        variableBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder addVariable(org.mojolang.mojo.postman.Variable value) {
      if (variableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableIsMutable();
        variable_.add(value);
        onChanged();
      } else {
        variableBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder addVariable(
        int index, org.mojolang.mojo.postman.Variable value) {
      if (variableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariableIsMutable();
        variable_.add(index, value);
        onChanged();
      } else {
        variableBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder addVariable(
        org.mojolang.mojo.postman.Variable.Builder builderForValue) {
      if (variableBuilder_ == null) {
        ensureVariableIsMutable();
        variable_.add(builderForValue.build());
        onChanged();
      } else {
        variableBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder addVariable(
        int index, org.mojolang.mojo.postman.Variable.Builder builderForValue) {
      if (variableBuilder_ == null) {
        ensureVariableIsMutable();
        variable_.add(index, builderForValue.build());
        onChanged();
      } else {
        variableBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder addAllVariable(
        java.lang.Iterable<? extends org.mojolang.mojo.postman.Variable> values) {
      if (variableBuilder_ == null) {
        ensureVariableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variable_);
        onChanged();
      } else {
        variableBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder clearVariable() {
      if (variableBuilder_ == null) {
        variable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        variableBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public Builder removeVariable(int index) {
      if (variableBuilder_ == null) {
        ensureVariableIsMutable();
        variable_.remove(index);
        onChanged();
      } else {
        variableBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public org.mojolang.mojo.postman.Variable.Builder getVariableBuilder(
        int index) {
      return getVariableFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
        int index) {
      if (variableBuilder_ == null) {
        return variable_.get(index);  } else {
        return variableBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
         getVariableOrBuilderList() {
      if (variableBuilder_ != null) {
        return variableBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variable_);
      }
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public org.mojolang.mojo.postman.Variable.Builder addVariableBuilder() {
      return getVariableFieldBuilder().addBuilder(
          org.mojolang.mojo.postman.Variable.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public org.mojolang.mojo.postman.Variable.Builder addVariableBuilder(
        int index) {
      return getVariableFieldBuilder().addBuilder(
          index, org.mojolang.mojo.postman.Variable.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Variable variable = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Variable.Builder> 
         getVariableBuilderList() {
      return getVariableFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Variable, org.mojolang.mojo.postman.Variable.Builder, org.mojolang.mojo.postman.VariableOrBuilder> 
        getVariableFieldBuilder() {
      if (variableBuilder_ == null) {
        variableBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.postman.Variable, org.mojolang.mojo.postman.Variable.Builder, org.mojolang.mojo.postman.VariableOrBuilder>(
                variable_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        variable_ = null;
      }
      return variableBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.postman.Collection)
  }

  // @@protoc_insertion_point(class_scope:mojo.postman.Collection)
  private static final org.mojolang.mojo.postman.Collection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.postman.Collection();
  }

  public static org.mojolang.mojo.postman.Collection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Collection>
      PARSER = new com.google.protobuf.AbstractParser<Collection>() {
    @java.lang.Override
    public Collection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Collection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Collection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.postman.Collection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

