// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/description.proto

package org.mojolang.mojo.postman;

public final class DescriptionProto {
  private DescriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Description_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Description_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036mojo/postman/description.proto\022\014mojo.p" +
      "ostman\"=\n\013Description\022\017\n\007content\030\001 \001(\t\022\014" +
      "\n\004type\030\002 \001(\t\022\017\n\007version\030\003 \001(\tBi\n\031org.moj" +
      "olang.mojo.postmanB\020DescriptionProtoP\001Z8" +
      "github.com/mojo-lang/postman/go/pkg/mojo" +
      "/postman;postmanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_postman_Description_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Description_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Description_descriptor,
        new java.lang.String[] { "Content", "Type", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
