// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/description.proto

package org.mojolang.mojo.postman;

public interface DescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Description)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
