// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/header.proto

package org.mojolang.mojo.postman;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031mojo/postman/header.proto\022\014mojo.postma" +
      "n\032\036mojo/postman/description.proto\"f\n\006Hea" +
      "der\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\020\n\010disab" +
      "led\030\003 \001(\010\022.\n\013description\030\004 \001(\0132\031.mojo.po" +
      "stman.DescriptionBd\n\031org.mojolang.mojo.p" +
      "ostmanB\013HeaderProtoP\001Z8github.com/mojo-l" +
      "ang/postman/go/pkg/mojo/postman;postmanb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
        });
    internal_static_mojo_postman_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Header_descriptor,
        new java.lang.String[] { "Key", "Value", "Disabled", "Description", });
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
