// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/info.proto

package org.mojolang.mojo.postman;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string postman_id = 2 [(.mojo.alias) = "_postman_id"];</code>
   * @return The postmanId.
   */
  java.lang.String getPostmanId();
  /**
   * <code>string postman_id = 2 [(.mojo.alias) = "_postman_id"];</code>
   * @return The bytes for postmanId.
   */
  com.google.protobuf.ByteString
      getPostmanIdBytes();

  /**
   * <code>.mojo.postman.Description description = 3;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.mojo.postman.Description description = 3;</code>
   * @return The description.
   */
  org.mojolang.mojo.postman.Description getDescription();
  /**
   * <code>.mojo.postman.Description description = 3;</code>
   */
  org.mojolang.mojo.postman.DescriptionOrBuilder getDescriptionOrBuilder();

  /**
   * <code>.mojo.core.Version version = 5;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>.mojo.core.Version version = 5;</code>
   * @return The version.
   */
  org.mojolang.mojo.core.Version getVersion();
  /**
   * <code>.mojo.core.Version version = 5;</code>
   */
  org.mojolang.mojo.core.VersionOrBuilder getVersionOrBuilder();

  /**
   * <code>string schema = 6;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <code>string schema = 6;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();
}
