// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/item_group.proto

package org.mojolang.mojo.postman;

public final class ItemGroupProto {
  private ItemGroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_ItemGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_ItemGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mojo/postman/item_group.proto\022\014mojo.po" +
      "stman\032\036mojo/postman/description.proto\032\027m" +
      "ojo/postman/item.proto\032\033mojo/postman/var" +
      "iable.proto\"\225\001\n\tItemGroup\022\014\n\004name\030\001 \001(\t\022" +
      ".\n\013description\030\002 \001(\0132\031.mojo.postman.Desc" +
      "ription\022(\n\010variable\030\003 \003(\0132\026.mojo.postman" +
      ".Variable\022 \n\004item\030\005 \003(\0132\022.mojo.postman.I" +
      "temBg\n\031org.mojolang.mojo.postmanB\016ItemGr" +
      "oupProtoP\001Z8github.com/mojo-lang/postman" +
      "/go/pkg/mojo/postman;postmanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
          org.mojolang.mojo.postman.ItemProto.getDescriptor(),
          org.mojolang.mojo.postman.VariableProto.getDescriptor(),
        });
    internal_static_mojo_postman_ItemGroup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_ItemGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_ItemGroup_descriptor,
        new java.lang.String[] { "Name", "Description", "Variable", "Item", });
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
    org.mojolang.mojo.postman.ItemProto.getDescriptor();
    org.mojolang.mojo.postman.VariableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
