// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/item_group.proto

package org.mojolang.mojo.postman;

public interface ItemGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.ItemGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.mojo.postman.Description description = 2;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.mojo.postman.Description description = 2;</code>
   * @return The description.
   */
  org.mojolang.mojo.postman.Description getDescription();
  /**
   * <code>.mojo.postman.Description description = 2;</code>
   */
  org.mojolang.mojo.postman.DescriptionOrBuilder getDescriptionOrBuilder();

  /**
   * <code>repeated .mojo.postman.Variable variable = 3;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Variable> 
      getVariableList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 3;</code>
   */
  org.mojolang.mojo.postman.Variable getVariable(int index);
  /**
   * <code>repeated .mojo.postman.Variable variable = 3;</code>
   */
  int getVariableCount();
  /**
   * <code>repeated .mojo.postman.Variable variable = 3;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
      getVariableOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 3;</code>
   */
  org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
      int index);

  /**
   * <code>repeated .mojo.postman.Item item = 5;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Item> 
      getItemList();
  /**
   * <code>repeated .mojo.postman.Item item = 5;</code>
   */
  org.mojolang.mojo.postman.Item getItem(int index);
  /**
   * <code>repeated .mojo.postman.Item item = 5;</code>
   */
  int getItemCount();
  /**
   * <code>repeated .mojo.postman.Item item = 5;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.ItemOrBuilder> 
      getItemOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Item item = 5;</code>
   */
  org.mojolang.mojo.postman.ItemOrBuilder getItemOrBuilder(
      int index);
}
