// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/item.proto

package org.mojolang.mojo.postman;

public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.mojo.postman.Description description = 3;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.mojo.postman.Description description = 3;</code>
   * @return The description.
   */
  org.mojolang.mojo.postman.Description getDescription();
  /**
   * <code>.mojo.postman.Description description = 3;</code>
   */
  org.mojolang.mojo.postman.DescriptionOrBuilder getDescriptionOrBuilder();

  /**
   * <code>repeated .mojo.postman.Variable variable = 4 [(.mojo.reference) = ""];</code>
   */
  java.util.List<org.mojolang.mojo.postman.Variable> 
      getVariableList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 4 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.Variable getVariable(int index);
  /**
   * <code>repeated .mojo.postman.Variable variable = 4 [(.mojo.reference) = ""];</code>
   */
  int getVariableCount();
  /**
   * <code>repeated .mojo.postman.Variable variable = 4 [(.mojo.reference) = ""];</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
      getVariableOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 4 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
      int index);

  /**
   * <code>repeated .mojo.postman.Item item = 10 [(.mojo.reference) = ""];</code>
   */
  java.util.List<org.mojolang.mojo.postman.Item> 
      getItemList();
  /**
   * <code>repeated .mojo.postman.Item item = 10 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.Item getItem(int index);
  /**
   * <code>repeated .mojo.postman.Item item = 10 [(.mojo.reference) = ""];</code>
   */
  int getItemCount();
  /**
   * <code>repeated .mojo.postman.Item item = 10 [(.mojo.reference) = ""];</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.ItemOrBuilder> 
      getItemOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Item item = 10 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.ItemOrBuilder getItemOrBuilder(
      int index);

  /**
   * <code>.mojo.postman.Request request = 11;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.mojo.postman.Request request = 11;</code>
   * @return The request.
   */
  org.mojolang.mojo.postman.Request getRequest();
  /**
   * <code>.mojo.postman.Request request = 11;</code>
   */
  org.mojolang.mojo.postman.RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>repeated .mojo.postman.Response response = 12 [(.mojo.reference) = ""];</code>
   */
  java.util.List<org.mojolang.mojo.postman.Response> 
      getResponseList();
  /**
   * <code>repeated .mojo.postman.Response response = 12 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.Response getResponse(int index);
  /**
   * <code>repeated .mojo.postman.Response response = 12 [(.mojo.reference) = ""];</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .mojo.postman.Response response = 12 [(.mojo.reference) = ""];</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.ResponseOrBuilder> 
      getResponseOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Response response = 12 [(.mojo.reference) = ""];</code>
   */
  org.mojolang.mojo.postman.ResponseOrBuilder getResponseOrBuilder(
      int index);
}
