// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/item.proto

package org.mojolang.mojo.postman;

public final class ItemProto {
  private ItemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/postman/item.proto\022\014mojo.postman\032" +
      "\017mojo/mojo.proto\032\036mojo/postman/descripti" +
      "on.proto\032\032mojo/postman/request.proto\032\033mo" +
      "jo/postman/response.proto\032\033mojo/postman/" +
      "variable.proto\"\200\002\n\004Item\022\n\n\002id\030\001 \001(\t\022\014\n\004n" +
      "ame\030\002 \001(\t\022.\n\013description\030\003 \001(\0132\031.mojo.po" +
      "stman.Description\022.\n\010variable\030\004 \003(\0132\026.mo" +
      "jo.postman.VariableB\004\332\317$\000\022&\n\004item\030\n \003(\0132" +
      "\022.mojo.postman.ItemB\004\332\317$\000\022&\n\007request\030\013 \001" +
      "(\0132\025.mojo.postman.Request\022.\n\010response\030\014 " +
      "\003(\0132\026.mojo.postman.ResponseB\004\332\317$\000Bb\n\031org" +
      ".mojolang.mojo.postmanB\tItemProtoP\001Z8git" +
      "hub.com/mojo-lang/postman/go/pkg/mojo/po" +
      "stman;postmanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.MojoProtos.getDescriptor(),
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
          org.mojolang.mojo.postman.RequestProto.getDescriptor(),
          org.mojolang.mojo.postman.ResponseProto.getDescriptor(),
          org.mojolang.mojo.postman.VariableProto.getDescriptor(),
        });
    internal_static_mojo_postman_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Item_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Variable", "Item", "Request", "Response", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.MojoProtos.reference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.MojoProtos.getDescriptor();
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
    org.mojolang.mojo.postman.RequestProto.getDescriptor();
    org.mojolang.mojo.postman.ResponseProto.getDescriptor();
    org.mojolang.mojo.postman.VariableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
