// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/postman.proto

package org.mojolang.mojo.postman;

public final class PostmanProto {
  private PostmanProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Collection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Collection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_CollectionItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_CollectionItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_ItemGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_ItemGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/postman/postman.proto\022\014mojo.postm" +
      "an\032\036mojo/postman/description.proto\032\027mojo" +
      "/postman/info.proto\032\027mojo/postman/item.p" +
      "roto\032\033mojo/postman/variable.proto\"\204\001\n\nCo" +
      "llection\022 \n\004info\030\001 \001(\0132\022.mojo.postman.In" +
      "fo\022*\n\004item\030\002 \003(\0132\034.mojo.postman.Collecti" +
      "onItem\022(\n\010variable\030\005 \003(\0132\026.mojo.postman." +
      "Variable\"~\n\016CollectionItem\022&\n\010item_val\030\001" +
      " \001(\0132\022.mojo.postman.ItemH\000\0221\n\016item_group" +
      "_val\030\002 \001(\0132\027.mojo.postman.ItemGroupH\000B\021\n" +
      "\017collection_item\"\237\001\n\tItemGroup\022\014\n\004name\030\001" +
      " \001(\t\022.\n\013description\030\002 \001(\0132\031.mojo.postman" +
      ".Description\022(\n\010variable\030\003 \003(\0132\026.mojo.po" +
      "stman.Variable\022*\n\004item\030\005 \003(\0132\034.mojo.post" +
      "man.CollectionItemBe\n\031org.mojolang.mojo." +
      "postmanB\014PostmanProtoP\001Z8github.com/mojo" +
      "-lang/postman/go/pkg/mojo/postman;postma" +
      "nb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
          org.mojolang.mojo.postman.InfoProto.getDescriptor(),
          org.mojolang.mojo.postman.ItemProto.getDescriptor(),
          org.mojolang.mojo.postman.VariableProto.getDescriptor(),
        });
    internal_static_mojo_postman_Collection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Collection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Collection_descriptor,
        new java.lang.String[] { "Info", "Item", "Variable", });
    internal_static_mojo_postman_CollectionItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_postman_CollectionItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_CollectionItem_descriptor,
        new java.lang.String[] { "ItemVal", "ItemGroupVal", "CollectionItem", });
    internal_static_mojo_postman_ItemGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_postman_ItemGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_ItemGroup_descriptor,
        new java.lang.String[] { "Name", "Description", "Variable", "Item", });
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
    org.mojolang.mojo.postman.InfoProto.getDescriptor();
    org.mojolang.mojo.postman.ItemProto.getDescriptor();
    org.mojolang.mojo.postman.VariableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
