// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/request.proto

package org.mojolang.mojo.postman;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Request_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Request_Body_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Request_UrlEncodedParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Request_UrlEncodedParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Request_FormParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Request_FormParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Request_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Request_File_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032mojo/postman/request.proto\022\014mojo.postm" +
      "an\032\025mojo/core/value.proto\032\036mojo/postman/" +
      "description.proto\032\031mojo/postman/header.p" +
      "roto\032\026mojo/postman/url.proto\"\223\006\n\007Request" +
      "\022\036\n\003url\030\001 \001(\0132\021.mojo.postman.Url\022\016\n\006meth" +
      "od\030\003 \001(\t\022.\n\013description\030\004 \001(\0132\031.mojo.pos" +
      "tman.Description\022$\n\006header\030\005 \003(\0132\024.mojo." +
      "postman.Header\022(\n\004body\030\010 \001(\0132\032.mojo.post" +
      "man.Request.Body\032\233\002\n\004Body\022\014\n\004mode\030\001 \001(\t\022" +
      "\013\n\003raw\030\002 \001(\t\022=\n\nurlencoded\030\003 \003(\0132).mojo." +
      "postman.Request.UrlEncodedParameter\0225\n\010f" +
      "ormdata\030\004 \003(\0132#.mojo.postman.Request.For" +
      "mParameter\022(\n\004file\030\005 \001(\0132\032.mojo.postman." +
      "Request.File\022\"\n\007graphql\030\006 \001(\0132\021.mojo.cor" +
      "e.Object\022\"\n\007options\030\007 \001(\0132\021.mojo.core.Ob" +
      "ject\022\020\n\010disabled\030\010 \001(\010\032s\n\023UrlEncodedPara" +
      "meter\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\020\n\010dis" +
      "abled\030\003 \001(\010\022.\n\013description\030\004 \001(\0132\031.mojo." +
      "postman.Description\032\236\001\n\rFormParameter\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\013\n\003src\030\003 \001(\t\022\020" +
      "\n\010disabled\030\004 \001(\010\022\014\n\004type\030\005 \001(\t\022\024\n\014conten" +
      "t_type\030\006 \001(\t\022.\n\013description\030\007 \001(\0132\031.mojo" +
      ".postman.Description\032$\n\004File\022\013\n\003src\030\001 \001(" +
      "\t\022\017\n\007content\030\002 \001(\tBe\n\031org.mojolang.mojo." +
      "postmanB\014RequestProtoP\001Z8github.com/mojo" +
      "-lang/postman/go/pkg/mojo/postman;postma" +
      "nb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
          org.mojolang.mojo.postman.HeaderProto.getDescriptor(),
          org.mojolang.mojo.postman.UrlProto.getDescriptor(),
        });
    internal_static_mojo_postman_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Request_descriptor,
        new java.lang.String[] { "Url", "Method", "Description", "Header", "Body", });
    internal_static_mojo_postman_Request_Body_descriptor =
      internal_static_mojo_postman_Request_descriptor.getNestedTypes().get(0);
    internal_static_mojo_postman_Request_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Request_Body_descriptor,
        new java.lang.String[] { "Mode", "Raw", "Urlencoded", "Formdata", "File", "Graphql", "Options", "Disabled", });
    internal_static_mojo_postman_Request_UrlEncodedParameter_descriptor =
      internal_static_mojo_postman_Request_descriptor.getNestedTypes().get(1);
    internal_static_mojo_postman_Request_UrlEncodedParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Request_UrlEncodedParameter_descriptor,
        new java.lang.String[] { "Key", "Value", "Disabled", "Description", });
    internal_static_mojo_postman_Request_FormParameter_descriptor =
      internal_static_mojo_postman_Request_descriptor.getNestedTypes().get(2);
    internal_static_mojo_postman_Request_FormParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Request_FormParameter_descriptor,
        new java.lang.String[] { "Key", "Value", "Src", "Disabled", "Type", "ContentType", "Description", });
    internal_static_mojo_postman_Request_File_descriptor =
      internal_static_mojo_postman_Request_descriptor.getNestedTypes().get(3);
    internal_static_mojo_postman_Request_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Request_File_descriptor,
        new java.lang.String[] { "Src", "Content", });
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
    org.mojolang.mojo.postman.HeaderProto.getDescriptor();
    org.mojolang.mojo.postman.UrlProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
