// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/response.proto

package org.mojolang.mojo.postman;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   * @return Whether the originalRequest field is set.
   */
  boolean hasOriginalRequest();
  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   * @return The originalRequest.
   */
  org.mojolang.mojo.postman.Request getOriginalRequest();
  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   */
  org.mojolang.mojo.postman.RequestOrBuilder getOriginalRequestOrBuilder();

  /**
   * <code>int32 response_time = 3;</code>
   * @return The responseTime.
   */
  int getResponseTime();

  /**
   * <code>.mojo.core.Object timings = 4;</code>
   * @return Whether the timings field is set.
   */
  boolean hasTimings();
  /**
   * <code>.mojo.core.Object timings = 4;</code>
   * @return The timings.
   */
  org.mojolang.mojo.core.Object getTimings();
  /**
   * <code>.mojo.core.Object timings = 4;</code>
   */
  org.mojolang.mojo.core.ObjectOrBuilder getTimingsOrBuilder();

  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Header> 
      getHeaderList();
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  org.mojolang.mojo.postman.Header getHeader(int index);
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  int getHeaderCount();
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.HeaderOrBuilder> 
      getHeaderOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  org.mojolang.mojo.postman.HeaderOrBuilder getHeaderOrBuilder(
      int index);

  /**
   * <code>string body = 10;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 10;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string status = 11;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 11;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 code = 12;</code>
   * @return The code.
   */
  int getCode();
}
