// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/response.proto

package org.mojolang.mojo.postman;

/**
 * Protobuf type {@code mojo.postman.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.postman.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    id_ = "";
    header_ = java.util.Collections.emptyList();
    body_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.postman.ResponseProto.internal_static_mojo_postman_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.postman.ResponseProto.internal_static_mojo_postman_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.postman.Response.class, org.mojolang.mojo.postman.Response.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_REQUEST_FIELD_NUMBER = 2;
  private org.mojolang.mojo.postman.Request originalRequest_;
  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   * @return Whether the originalRequest field is set.
   */
  @java.lang.Override
  public boolean hasOriginalRequest() {
    return originalRequest_ != null;
  }
  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   * @return The originalRequest.
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.Request getOriginalRequest() {
    return originalRequest_ == null ? org.mojolang.mojo.postman.Request.getDefaultInstance() : originalRequest_;
  }
  /**
   * <code>.mojo.postman.Request original_request = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.RequestOrBuilder getOriginalRequestOrBuilder() {
    return originalRequest_ == null ? org.mojolang.mojo.postman.Request.getDefaultInstance() : originalRequest_;
  }

  public static final int RESPONSE_TIME_FIELD_NUMBER = 3;
  private int responseTime_ = 0;
  /**
   * <code>int32 response_time = 3;</code>
   * @return The responseTime.
   */
  @java.lang.Override
  public int getResponseTime() {
    return responseTime_;
  }

  public static final int TIMINGS_FIELD_NUMBER = 4;
  private org.mojolang.mojo.core.Object timings_;
  /**
   * <code>.mojo.core.Object timings = 4;</code>
   * @return Whether the timings field is set.
   */
  @java.lang.Override
  public boolean hasTimings() {
    return timings_ != null;
  }
  /**
   * <code>.mojo.core.Object timings = 4;</code>
   * @return The timings.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Object getTimings() {
    return timings_ == null ? org.mojolang.mojo.core.Object.getDefaultInstance() : timings_;
  }
  /**
   * <code>.mojo.core.Object timings = 4;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.ObjectOrBuilder getTimingsOrBuilder() {
    return timings_ == null ? org.mojolang.mojo.core.Object.getDefaultInstance() : timings_;
  }

  public static final int HEADER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.mojolang.mojo.postman.Header> header_;
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.postman.Header> getHeaderList() {
    return header_;
  }
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.postman.HeaderOrBuilder> 
      getHeaderOrBuilderList() {
    return header_;
  }
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  @java.lang.Override
  public int getHeaderCount() {
    return header_.size();
  }
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.Header getHeader(int index) {
    return header_.get(index);
  }
  /**
   * <code>repeated .mojo.postman.Header header = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.postman.HeaderOrBuilder getHeaderOrBuilder(
      int index) {
    return header_.get(index);
  }

  public static final int BODY_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object body_ = "";
  /**
   * <code>string body = 10;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 10;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 11;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 11;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 12;
  private int code_ = 0;
  /**
   * <code>int32 code = 12;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (originalRequest_ != null) {
      output.writeMessage(2, getOriginalRequest());
    }
    if (responseTime_ != 0) {
      output.writeInt32(3, responseTime_);
    }
    if (timings_ != null) {
      output.writeMessage(4, getTimings());
    }
    for (int i = 0; i < header_.size(); i++) {
      output.writeMessage(5, header_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, status_);
    }
    if (code_ != 0) {
      output.writeInt32(12, code_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (originalRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOriginalRequest());
    }
    if (responseTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, responseTime_);
    }
    if (timings_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimings());
    }
    for (int i = 0; i < header_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, header_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, status_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, code_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.postman.Response)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.postman.Response other = (org.mojolang.mojo.postman.Response) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasOriginalRequest() != other.hasOriginalRequest()) return false;
    if (hasOriginalRequest()) {
      if (!getOriginalRequest()
          .equals(other.getOriginalRequest())) return false;
    }
    if (getResponseTime()
        != other.getResponseTime()) return false;
    if (hasTimings() != other.hasTimings()) return false;
    if (hasTimings()) {
      if (!getTimings()
          .equals(other.getTimings())) return false;
    }
    if (!getHeaderList()
        .equals(other.getHeaderList())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getCode()
        != other.getCode()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasOriginalRequest()) {
      hash = (37 * hash) + ORIGINAL_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalRequest().hashCode();
    }
    hash = (37 * hash) + RESPONSE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTime();
    if (hasTimings()) {
      hash = (37 * hash) + TIMINGS_FIELD_NUMBER;
      hash = (53 * hash) + getTimings().hashCode();
    }
    if (getHeaderCount() > 0) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderList().hashCode();
    }
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.postman.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.postman.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.postman.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.postman.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.postman.Response)
      org.mojolang.mojo.postman.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.postman.ResponseProto.internal_static_mojo_postman_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.postman.ResponseProto.internal_static_mojo_postman_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.postman.Response.class, org.mojolang.mojo.postman.Response.Builder.class);
    }

    // Construct using org.mojolang.mojo.postman.Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      responseTime_ = 0;
      timings_ = null;
      if (timingsBuilder_ != null) {
        timingsBuilder_.dispose();
        timingsBuilder_ = null;
      }
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
      } else {
        header_ = null;
        headerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      body_ = "";
      status_ = "";
      code_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.postman.ResponseProto.internal_static_mojo_postman_Response_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Response getDefaultInstanceForType() {
      return org.mojolang.mojo.postman.Response.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Response build() {
      org.mojolang.mojo.postman.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.postman.Response buildPartial() {
      org.mojolang.mojo.postman.Response result = new org.mojolang.mojo.postman.Response(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.mojolang.mojo.postman.Response result) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          header_ = java.util.Collections.unmodifiableList(header_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
    }

    private void buildPartial0(org.mojolang.mojo.postman.Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.originalRequest_ = originalRequestBuilder_ == null
            ? originalRequest_
            : originalRequestBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.responseTime_ = responseTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timings_ = timingsBuilder_ == null
            ? timings_
            : timingsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.body_ = body_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.code_ = code_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.postman.Response) {
        return mergeFrom((org.mojolang.mojo.postman.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.postman.Response other) {
      if (other == org.mojolang.mojo.postman.Response.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOriginalRequest()) {
        mergeOriginalRequest(other.getOriginalRequest());
      }
      if (other.getResponseTime() != 0) {
        setResponseTime(other.getResponseTime());
      }
      if (other.hasTimings()) {
        mergeTimings(other.getTimings());
      }
      if (headerBuilder_ == null) {
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
      } else {
        if (!other.header_.isEmpty()) {
          if (headerBuilder_.isEmpty()) {
            headerBuilder_.dispose();
            headerBuilder_ = null;
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000010);
            headerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeaderFieldBuilder() : null;
          } else {
            headerBuilder_.addAllMessages(other.header_);
          }
        }
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getOriginalRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              responseTime_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  getTimingsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              org.mojolang.mojo.postman.Header m =
                  input.readMessage(
                      org.mojolang.mojo.postman.Header.parser(),
                      extensionRegistry);
              if (headerBuilder_ == null) {
                ensureHeaderIsMutable();
                header_.add(m);
              } else {
                headerBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 82: {
              body_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 82
            case 90: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 90
            case 96: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.postman.Request originalRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.postman.Request, org.mojolang.mojo.postman.Request.Builder, org.mojolang.mojo.postman.RequestOrBuilder> originalRequestBuilder_;
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     * @return Whether the originalRequest field is set.
     */
    public boolean hasOriginalRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     * @return The originalRequest.
     */
    public org.mojolang.mojo.postman.Request getOriginalRequest() {
      if (originalRequestBuilder_ == null) {
        return originalRequest_ == null ? org.mojolang.mojo.postman.Request.getDefaultInstance() : originalRequest_;
      } else {
        return originalRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public Builder setOriginalRequest(org.mojolang.mojo.postman.Request value) {
      if (originalRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        originalRequest_ = value;
      } else {
        originalRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public Builder setOriginalRequest(
        org.mojolang.mojo.postman.Request.Builder builderForValue) {
      if (originalRequestBuilder_ == null) {
        originalRequest_ = builderForValue.build();
      } else {
        originalRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public Builder mergeOriginalRequest(org.mojolang.mojo.postman.Request value) {
      if (originalRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          originalRequest_ != null &&
          originalRequest_ != org.mojolang.mojo.postman.Request.getDefaultInstance()) {
          getOriginalRequestBuilder().mergeFrom(value);
        } else {
          originalRequest_ = value;
        }
      } else {
        originalRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public Builder clearOriginalRequest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public org.mojolang.mojo.postman.Request.Builder getOriginalRequestBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getOriginalRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    public org.mojolang.mojo.postman.RequestOrBuilder getOriginalRequestOrBuilder() {
      if (originalRequestBuilder_ != null) {
        return originalRequestBuilder_.getMessageOrBuilder();
      } else {
        return originalRequest_ == null ?
            org.mojolang.mojo.postman.Request.getDefaultInstance() : originalRequest_;
      }
    }
    /**
     * <code>.mojo.postman.Request original_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.postman.Request, org.mojolang.mojo.postman.Request.Builder, org.mojolang.mojo.postman.RequestOrBuilder> 
        getOriginalRequestFieldBuilder() {
      if (originalRequestBuilder_ == null) {
        originalRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.postman.Request, org.mojolang.mojo.postman.Request.Builder, org.mojolang.mojo.postman.RequestOrBuilder>(
                getOriginalRequest(),
                getParentForChildren(),
                isClean());
        originalRequest_ = null;
      }
      return originalRequestBuilder_;
    }

    private int responseTime_ ;
    /**
     * <code>int32 response_time = 3;</code>
     * @return The responseTime.
     */
    @java.lang.Override
    public int getResponseTime() {
      return responseTime_;
    }
    /**
     * <code>int32 response_time = 3;</code>
     * @param value The responseTime to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTime(int value) {
      
      responseTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 response_time = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      responseTime_ = 0;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Object timings_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Object, org.mojolang.mojo.core.Object.Builder, org.mojolang.mojo.core.ObjectOrBuilder> timingsBuilder_;
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     * @return Whether the timings field is set.
     */
    public boolean hasTimings() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     * @return The timings.
     */
    public org.mojolang.mojo.core.Object getTimings() {
      if (timingsBuilder_ == null) {
        return timings_ == null ? org.mojolang.mojo.core.Object.getDefaultInstance() : timings_;
      } else {
        return timingsBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public Builder setTimings(org.mojolang.mojo.core.Object value) {
      if (timingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timings_ = value;
      } else {
        timingsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public Builder setTimings(
        org.mojolang.mojo.core.Object.Builder builderForValue) {
      if (timingsBuilder_ == null) {
        timings_ = builderForValue.build();
      } else {
        timingsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public Builder mergeTimings(org.mojolang.mojo.core.Object value) {
      if (timingsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          timings_ != null &&
          timings_ != org.mojolang.mojo.core.Object.getDefaultInstance()) {
          getTimingsBuilder().mergeFrom(value);
        } else {
          timings_ = value;
        }
      } else {
        timingsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public Builder clearTimings() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timings_ = null;
      if (timingsBuilder_ != null) {
        timingsBuilder_.dispose();
        timingsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public org.mojolang.mojo.core.Object.Builder getTimingsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getTimingsFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    public org.mojolang.mojo.core.ObjectOrBuilder getTimingsOrBuilder() {
      if (timingsBuilder_ != null) {
        return timingsBuilder_.getMessageOrBuilder();
      } else {
        return timings_ == null ?
            org.mojolang.mojo.core.Object.getDefaultInstance() : timings_;
      }
    }
    /**
     * <code>.mojo.core.Object timings = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Object, org.mojolang.mojo.core.Object.Builder, org.mojolang.mojo.core.ObjectOrBuilder> 
        getTimingsFieldBuilder() {
      if (timingsBuilder_ == null) {
        timingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Object, org.mojolang.mojo.core.Object.Builder, org.mojolang.mojo.core.ObjectOrBuilder>(
                getTimings(),
                getParentForChildren(),
                isClean());
        timings_ = null;
      }
      return timingsBuilder_;
    }

    private java.util.List<org.mojolang.mojo.postman.Header> header_ =
      java.util.Collections.emptyList();
    private void ensureHeaderIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        header_ = new java.util.ArrayList<org.mojolang.mojo.postman.Header>(header_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Header, org.mojolang.mojo.postman.Header.Builder, org.mojolang.mojo.postman.HeaderOrBuilder> headerBuilder_;

    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Header> getHeaderList() {
      if (headerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(header_);
      } else {
        return headerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public int getHeaderCount() {
      if (headerBuilder_ == null) {
        return header_.size();
      } else {
        return headerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public org.mojolang.mojo.postman.Header getHeader(int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);
      } else {
        return headerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder setHeader(
        int index, org.mojolang.mojo.postman.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
      } else {
        headerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder setHeader(
        int index, org.mojolang.mojo.postman.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.set(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder addHeader(org.mojolang.mojo.postman.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
      } else {
        headerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder addHeader(
        int index, org.mojolang.mojo.postman.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(index, value);
        onChanged();
      } else {
        headerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder addHeader(
        org.mojolang.mojo.postman.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder addHeader(
        int index, org.mojolang.mojo.postman.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder addAllHeader(
        java.lang.Iterable<? extends org.mojolang.mojo.postman.Header> values) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, header_);
        onChanged();
      } else {
        headerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        headerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public Builder removeHeader(int index) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.remove(index);
        onChanged();
      } else {
        headerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public org.mojolang.mojo.postman.Header.Builder getHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public org.mojolang.mojo.postman.HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);  } else {
        return headerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.postman.HeaderOrBuilder> 
         getHeaderOrBuilderList() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(header_);
      }
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public org.mojolang.mojo.postman.Header.Builder addHeaderBuilder() {
      return getHeaderFieldBuilder().addBuilder(
          org.mojolang.mojo.postman.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public org.mojolang.mojo.postman.Header.Builder addHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().addBuilder(
          index, org.mojolang.mojo.postman.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.postman.Header header = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.postman.Header.Builder> 
         getHeaderBuilderList() {
      return getHeaderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.postman.Header, org.mojolang.mojo.postman.Header.Builder, org.mojolang.mojo.postman.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.postman.Header, org.mojolang.mojo.postman.Header.Builder, org.mojolang.mojo.postman.HeaderOrBuilder>(
                header_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 10;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 10;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 10;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      body_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      body_ = getDefaultInstance().getBody();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string body = 10;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      body_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 11;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 11;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 11;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 11;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 12;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 12;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000080);
      code_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.postman.Response)
  }

  // @@protoc_insertion_point(class_scope:mojo.postman.Response)
  private static final org.mojolang.mojo.postman.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.postman.Response();
  }

  public static org.mojolang.mojo.postman.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.postman.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

