// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/url.proto

package org.mojolang.mojo.postman;

public interface UrlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Url)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string raw = 1;</code>
   * @return The raw.
   */
  java.lang.String getRaw();
  /**
   * <code>string raw = 1;</code>
   * @return The bytes for raw.
   */
  com.google.protobuf.ByteString
      getRawBytes();

  /**
   * <code>string protocol = 2;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <code>string protocol = 2;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <code>repeated string host = 3;</code>
   * @return A list containing the host.
   */
  java.util.List<java.lang.String>
      getHostList();
  /**
   * <code>repeated string host = 3;</code>
   * @return The count of host.
   */
  int getHostCount();
  /**
   * <code>repeated string host = 3;</code>
   * @param index The index of the element to return.
   * @return The host at the given index.
   */
  java.lang.String getHost(int index);
  /**
   * <code>repeated string host = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the host at the given index.
   */
  com.google.protobuf.ByteString
      getHostBytes(int index);

  /**
   * <code>repeated .mojo.postman.Url.PathSegment path = 4;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Url.PathSegment> 
      getPathList();
  /**
   * <code>repeated .mojo.postman.Url.PathSegment path = 4;</code>
   */
  org.mojolang.mojo.postman.Url.PathSegment getPath(int index);
  /**
   * <code>repeated .mojo.postman.Url.PathSegment path = 4;</code>
   */
  int getPathCount();
  /**
   * <code>repeated .mojo.postman.Url.PathSegment path = 4;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.Url.PathSegmentOrBuilder> 
      getPathOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Url.PathSegment path = 4;</code>
   */
  org.mojolang.mojo.postman.Url.PathSegmentOrBuilder getPathOrBuilder(
      int index);

  /**
   * <code>string port = 5;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <code>string port = 5;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();

  /**
   * <code>repeated .mojo.postman.Url.QueryParam query = 6;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Url.QueryParam> 
      getQueryList();
  /**
   * <code>repeated .mojo.postman.Url.QueryParam query = 6;</code>
   */
  org.mojolang.mojo.postman.Url.QueryParam getQuery(int index);
  /**
   * <code>repeated .mojo.postman.Url.QueryParam query = 6;</code>
   */
  int getQueryCount();
  /**
   * <code>repeated .mojo.postman.Url.QueryParam query = 6;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.Url.QueryParamOrBuilder> 
      getQueryOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Url.QueryParam query = 6;</code>
   */
  org.mojolang.mojo.postman.Url.QueryParamOrBuilder getQueryOrBuilder(
      int index);

  /**
   * <code>string hash = 7;</code>
   * @return The hash.
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 7;</code>
   * @return The bytes for hash.
   */
  com.google.protobuf.ByteString
      getHashBytes();

  /**
   * <code>repeated .mojo.postman.Variable variable = 8;</code>
   */
  java.util.List<org.mojolang.mojo.postman.Variable> 
      getVariableList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 8;</code>
   */
  org.mojolang.mojo.postman.Variable getVariable(int index);
  /**
   * <code>repeated .mojo.postman.Variable variable = 8;</code>
   */
  int getVariableCount();
  /**
   * <code>repeated .mojo.postman.Variable variable = 8;</code>
   */
  java.util.List<? extends org.mojolang.mojo.postman.VariableOrBuilder> 
      getVariableOrBuilderList();
  /**
   * <code>repeated .mojo.postman.Variable variable = 8;</code>
   */
  org.mojolang.mojo.postman.VariableOrBuilder getVariableOrBuilder(
      int index);
}
