// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/url.proto

package org.mojolang.mojo.postman;

public final class UrlProto {
  private UrlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Url_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Url_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Url_PathSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Url_PathSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Url_QueryParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Url_QueryParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mojo/postman/url.proto\022\014mojo.postman\032\036" +
      "mojo/postman/description.proto\032\033mojo/pos" +
      "tman/variable.proto\"\352\002\n\003Url\022\013\n\003raw\030\001 \001(\t" +
      "\022\020\n\010protocol\030\002 \001(\t\022\014\n\004host\030\003 \003(\t\022+\n\004path" +
      "\030\004 \003(\0132\035.mojo.postman.Url.PathSegment\022\014\n" +
      "\004port\030\005 \001(\t\022+\n\005query\030\006 \003(\0132\034.mojo.postma" +
      "n.Url.QueryParam\022\014\n\004hash\030\007 \001(\t\022(\n\010variab" +
      "le\030\010 \003(\0132\026.mojo.postman.Variable\032*\n\013Path" +
      "Segment\022\014\n\004type\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\032j\n\n" +
      "QueryParam\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\020" +
      "\n\010disabled\030\003 \001(\010\022.\n\013description\030\004 \001(\0132\031." +
      "mojo.postman.DescriptionBa\n\031org.mojolang" +
      ".mojo.postmanB\010UrlProtoP\001Z8github.com/mo" +
      "jo-lang/postman/go/pkg/mojo/postman;post" +
      "manb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
          org.mojolang.mojo.postman.VariableProto.getDescriptor(),
        });
    internal_static_mojo_postman_Url_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Url_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Url_descriptor,
        new java.lang.String[] { "Raw", "Protocol", "Host", "Path", "Port", "Query", "Hash", "Variable", });
    internal_static_mojo_postman_Url_PathSegment_descriptor =
      internal_static_mojo_postman_Url_descriptor.getNestedTypes().get(0);
    internal_static_mojo_postman_Url_PathSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Url_PathSegment_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_mojo_postman_Url_QueryParam_descriptor =
      internal_static_mojo_postman_Url_descriptor.getNestedTypes().get(1);
    internal_static_mojo_postman_Url_QueryParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Url_QueryParam_descriptor,
        new java.lang.String[] { "Key", "Value", "Disabled", "Description", });
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
    org.mojolang.mojo.postman.VariableProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
