// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/variable.proto

package org.mojolang.mojo.postman;

public interface VariableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.postman.Variable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.mojo.core.Value value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.mojo.core.Value value = 3;</code>
   * @return The value.
   */
  org.mojolang.mojo.core.Value getValue();
  /**
   * <code>.mojo.core.Value value = 3;</code>
   */
  org.mojolang.mojo.core.ValueOrBuilder getValueOrBuilder();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.mojo.postman.Description description = 6;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.mojo.postman.Description description = 6;</code>
   * @return The description.
   */
  org.mojolang.mojo.postman.Description getDescription();
  /**
   * <code>.mojo.postman.Description description = 6;</code>
   */
  org.mojolang.mojo.postman.DescriptionOrBuilder getDescriptionOrBuilder();

  /**
   * <code>bool system = 7;</code>
   * @return The system.
   */
  boolean getSystem();

  /**
   * <code>bool disabled = 8;</code>
   * @return The disabled.
   */
  boolean getDisabled();
}
