// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/postman/variable.proto

package org.mojolang.mojo.postman;

public final class VariableProto {
  private VariableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_postman_Variable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_postman_Variable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mojo/postman/variable.proto\022\014mojo.post" +
      "man\032\025mojo/core/value.proto\032\036mojo/postman" +
      "/description.proto\"\262\001\n\010Variable\022\n\n\002id\030\001 " +
      "\001(\t\022\013\n\003key\030\002 \001(\t\022\037\n\005value\030\003 \001(\0132\020.mojo.c" +
      "ore.Value\022\014\n\004type\030\004 \001(\t\022\014\n\004name\030\005 \001(\t\022.\n" +
      "\013description\030\006 \001(\0132\031.mojo.postman.Descri" +
      "ption\022\016\n\006system\030\007 \001(\010\022\020\n\010disabled\030\010 \001(\010B" +
      "f\n\031org.mojolang.mojo.postmanB\rVariablePr" +
      "otoP\001Z8github.com/mojo-lang/postman/go/p" +
      "kg/mojo/postman;postmanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojolang.mojo.postman.DescriptionProto.getDescriptor(),
        });
    internal_static_mojo_postman_Variable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_postman_Variable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_postman_Variable_descriptor,
        new java.lang.String[] { "Id", "Key", "Value", "Type", "Name", "Description", "System", "Disabled", });
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojolang.mojo.postman.DescriptionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
